---
- name: "Configure hostname"
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
  
- name: "Manage cli Packages"
  package:
    name:
      - "bash"
      - "bash-completion"
      - "tmux"
      - "wget"
      - "curl"
      - "htop"
      - "jq"
      - "podman"
    state: "present"
  become: true
  
- include_tasks: chrony.yml
- include_tasks: selinux.yml
- include_tasks: firewalld.yml
- include_tasks: tuned.yml
- include_tasks: pcp.yml
- include_tasks: cockpit.yml
- include_tasks: avahi.yml
