title: Technocidal
tagline: Apple, Software and other stuff
author:
  name: Johannes Ebeling
  email: hello@technocidal.com
description: Technocidal is created by me, Johannes Ebeling. I'm a father, software engineer and aspiring coffee snob.
url: "https://technocidal.com"

# Build settings
show_excerpts: true

theme: minima

minima:
  skin: auto
  social_links:
    twitter: technocidal
    github: technocidal

header_pages:
  - _pages/about.md
  - _pages/gear.md
  - _pages/resume.md

include:  
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - SECURITY.md
  - Brewfile
  - Brewfile.lock.json

plugins:
  - jekyll-feed
  - jekyll-seo-tag
