---
- name: "Configure timezone"
  community.general.timezone:
    name: "{{ timezone }}"
  become: true
  
- name: "Manage chrony Packages"
  ansible.builtin.package:
    name: "chrony"
    state: "present"
  become: true

- name: "Manage chrony Services"
  ansible.builtin.service:
    name: "chronyd.service"
    state: "started"
    enabled: true
  become: true